INSERT INTO pilgrimage_reviews (pilgrimage_id, reviewer_name, review_text, rating)
VALUES 
(1, 'Rajesh Kumar', 'A truly spiritual journey!', 5),
(2, 'Simran Patel', 'Incredibly peaceful and serene.', 4),
(3, 'Amit Singh', 'Felt blessed to be here.', 5),
(4, 'Priya Gupta', 'A wonderful experience overall.', 4),
(5, 'Kiran Mehta', 'Magnificent architecture.', 5),
(6, 'Ravi Sharma', 'Divine atmosphere.', 5),
(7, 'Anjali Verma', 'A place of great historical significance.', 4),
(8, 'Neha Reddy', 'Spiritually enriching.', 5),
(9, 'Rahul Das', 'A must-visit for spiritual seekers.', 5),
(10, 'Sneha Kapoor', 'The spiritual energy here is palpable.', 4),
(11, 'Arjun Jain', 'A sacred place of immense peace.', 5),
(12, 'Deepika Bhatia', 'Absolutely divine.', 4),
(13, 'Vikram Nair', 'Truly a spiritual haven.', 5),
(14, 'Pooja Chawla', 'A place of great sanctity.', 4),
(15, 'Manish Rao', 'Incredibly soul-stirring experience.', 5),
(16, 'Geeta Iyer', 'Felt blessed to be here.', 5),
(17, 'Rajiv Malhotra', 'A serene and peaceful place.', 4),
(18, 'Sunita Sharma', 'Deeply spiritual and fulfilling.', 5),
(19, 'Anita Desai', 'A beautiful and peaceful pilgrimage.', 4),
(20, 'Rohit Khanna', 'A truly divine experience.', 5);
