INSERT INTO hotel (hotel_name, address, city, state, country, star_rating, phone_number, email, website, amenities)
VALUES 
('The Oberoi', 'Dr. Zakir Hussain Marg', 'New Delhi', 'Delhi', 'India', 5, '01123903988', 'info@oberoidelhi.com', 'oberoidelhi.com', 'Pool, Spa, Free WiFi'),
('Taj Mahal Palace', 'Apollo Bunder', 'Mumbai', 'Maharashtra', 'India', 5, '02266653366', 'contact@tajmahalpalace.com', 'tajmahalpalace.com', 'Sea View, Butler Service, Spa'),
('Leela Palace', 'Diplomatic Enclave', 'New Delhi', 'Delhi', 'India', 5, '01139331234', 'info@leelapalace.com', 'leelapalace.com', 'Luxurious Rooms, Spa, Free WiFi'),
('ITC Grand', 'Velachery Road', 'Chennai', 'Tamil Nadu', 'India', 5, '04422253355', 'contact@itcgrandchola.com', 'itcgrandchola.com', 'Infinity Pool, Gym, Spa'),
('Radisson Blu', 'Outer Ring Road', 'Bangalore', 'Karnataka', 'India', 5, '08049004900', 'info@radissonblubangalore.com', 'radissonblubangalore.com', 'Pool, Business Center, Gym'),
('Hyatt Regency', 'Anna Salai', 'Chennai', 'Tamil Nadu', 'India', 5, '04461001234', 'contact@hyattregencychennai.com', 'hyattregencychennai.com', 'Spa, Pool, Free WiFi'),
('JW Marriott', 'Juhu Tara Road', 'Mumbai', 'Maharashtra', 'India', 5, '02266933344', 'info@jwmarriottmumbai.com', 'jwmarriottmumbai.com', 'Sea View, Pool, Spa'),
('The Lalit', 'Barakhamba Avenue', 'New Delhi', 'Delhi', 'India', 5, '01144447777', 'contact@thelalit.com', 'thelalit.com', 'Gym, Spa, Free WiFi'),
('Trident', 'Nariman Point', 'Mumbai', 'Maharashtra', 'India', 5, '02266323232', 'info@tridenthotels.com', 'tridenthotels.com', 'Pool, Business Center, Spa'),
('Vivanta', 'M G Road', 'Bangalore', 'Karnataka', 'India', 5, '08066604666', 'contact@vivantabangalore.com', 'vivantabangalore.com', 'Free WiFi, Gym, Spa'),
('Novotel', 'East India Dock Road', 'Kolkata', 'West Bengal', 'India', 5, '03366021234', 'info@novotelkolkata.com', 'novotelkolkata.com', 'Pool, Gym, Spa'),
('Sheraton', 'Brigade Gateway', 'Bangalore', 'Karnataka', 'India', 5, '08042520101', 'contact@sheratonbangalore.com', 'sheratonbangalore.com', 'Infinity Pool, Free WiFi, Spa'),
('Le Meridien', 'Sankey Road', 'Bangalore', 'Karnataka', 'India', 5, '08041331111', 'info@lemeridienbangalore.com', 'lemeridienbangalore.com', 'Business Center, Gym, Spa'),
('Courtyard Marriott', 'Ramdev Park', 'Mumbai', 'Maharashtra', 'India', 5, '02261363333', 'contact@courtyardmumbai.com', 'courtyardmumbai.com', 'Pool, Free WiFi, Gym'),
('ITC Maurya', 'Sardar Patel Marg', 'New Delhi', 'Delhi', 'India', 5, '01126112233', 'info@itcmaurya.com', 'itcmaurya.com', 'Spa, Free WiFi, Pool'),
('Taj Lands End', 'Bandra West', 'Mumbai', 'Maharashtra', 'India', 5, '02266681234', 'contact@tajlandsend.com', 'tajlandsend.com', 'Sea View, Spa, Pool'),
('The Westin', 'Mindspace', 'Hyderabad', 'Telangana', 'India', 5, '04067676767', 'info@westinhyderabad.com', 'westinhyderabad.com', 'Business Center, Gym, Spa'),
('Park Hyatt', 'Banjara Hills', 'Hyderabad', 'Telangana', 'India', 5, '04049491234', 'contact@parkhyatthyderabad.com', 'parkhyatthyderabad.com', 'Free WiFi, Pool, Spa'),
('Fairmont', 'Rajokri', 'New Delhi', 'Delhi', 'India', 5, '01147191234', 'info@fairmontnewdelhi.com', 'fairmontnewdelhi.com', 'Spa, Free WiFi, Gym'),
('Four Seasons', 'Dr. E. Moses Road', 'Mumbai', 'Maharashtra', 'India', 5, '02224818000', 'contact@fourseasonsmumbai.com', 'fourseasonsmumbai.com', 'Sea View, Spa, Free WiFi');
