INSERT INTO pilgrimage_reviews (pilgrimage_id, reviewer_name, review_text, rating) VALUES
(1, 'Anjali Sharma', 'A beautiful place with a rich history.', 5),
(2, 'Rajesh Kumar', 'The energy here is incredible.', 4),
(3, 'Priya Das', 'A must-visit for spiritual seekers.', 5),
(4, 'Ravi Singh', 'Absolutely breathtaking!', 5),
(5, 'Neeta Verma', 'A vibrant atmosphere.', 4),
(6, 'Mohit Agarwal', 'Peaceful and serene.', 4),
(7, 'Sita Patel', 'A spiritual journey like no other.', 5),
(8, 'Vikram Joshi', 'The scenery is stunning.', 5),
(9, 'Deepa Rani', 'A historic and sacred site.', 5),
(10, 'Karan Mehta', 'A beautiful temple in the hills.', 4),
(11, 'Alok Sharma', 'A serene experience.', 4),
(12, 'Nisha Reddy', 'An important pilgrimage site.', 5),
(13, 'Sunil Bhagat', 'Divine blessings everywhere.', 5),
(14, 'Pooja Joshi', 'A hidden gem.', 4),
(15, 'Ajay Kumar', 'Very peaceful and well maintained.', 4),
(16, 'Kavita Sharma', 'A wonderful spiritual experience.', 5),
(17, 'Anand Sinha', 'Rich in culture and tradition.', 5),
(18, 'Simran Kaur', 'A must-see for everyone.', 5),
(19, 'Amrit Singh', 'A historic and beautiful Gurdwara.', 5),
(20, 'Manpreet Kaur', 'A significant place for Sikhs.', 5),
(21, 'Ravinder Singh', 'A beautiful and peaceful place.', 4),
(22, 'Nirmal Singh', 'A great experience.', 4),
(23, 'Fatima Ali', 'The atmosphere is overwhelming.', 5),
(24, 'Hassan Mohamed', 'A remarkable experience.', 5),
(25, 'Sara Khan', 'A unique architectural beauty.', 5),
(26, 'Leyla Akdemir', 'Stunning architecture and history.', 5),
(27, 'Omar Farooq', 'A spiritual oasis.', 5),
(28, 'Amina Zayed', 'Very welcoming and beautiful.', 4),
(29, 'Marta Benti', 'A tranquil and inspiring place.', 5),
(30, 'Vladimir Ivanov', 'A stunning architectural wonder.', 5),
(31, 'Daniela Rossi', 'An important site for Christians.', 5),
(32, 'Emily Carter', 'A beautiful and peaceful cathedral.', 4),
(33, 'Liam Brown', 'A spectacular church.', 5),
(34, 'Olivia Smith', 'An iconic place of worship.', 5),
(35, 'Tara Nguyen', 'A peaceful place with beautiful surroundings.', 4),
(36, 'Chen Wei', 'A stunning example of ancient architecture.', 5),
(37, 'Kiran Thapa', 'A magnificent stupa with deep spiritual significance.', 5),
(38, 'Anisha Gurung', 'An important Buddhist site.', 5),
(39, 'Putu Sudarma', 'A beautiful temple on the cliffs.', 4),
(40, 'Ravi Jain', 'A serene and spiritual place.', 5),
(41, 'Aditi Mehta', 'Incredible architecture and history.', 5),
(42, 'Veerendra Patel', 'A beautiful and tranquil temple.', 5),
(43, 'Mei Ling', 'A peaceful place to reflect.', 4),
(44, 'Rajiv Ranjan', 'An amazing temple in Australia.', 5),
(45, 'Sohan Lal', 'A historic site with deep significance.', 5),
(46, 'Arjun Dastan', 'A lovely Parsi temple.', 4),
(47, 'Zara Khosravi', 'A beautiful fire temple.', 5),
(48, 'Reza Karam', 'A welcoming community.', 4),
(49, 'Nadia Safari', 'An impressive site with a rich history.', 5),
(50, 'Thandiwe Moyo', 'A serene place of worship.', 5);
