INSERT INTO pilgrimage (
        pilgrimage_id,
        pilgrimage_name,
        established_year,
        pilgrimage_address,
        city,
        state,
        country,
        committee,
        offerings,
        primary_deity,
        opening_month,
        closing_month,
        website,
        average_visitors,
        peak_month,
        off_month,
        religion,
        categories,
        registration_required
    )
VALUES (
        1,
        'Kashi Vishvanaath',
        1780,
        'Kashi Vishwanath Temple',
        'Varanasi',
        'Uttar Pradesh',
        'India',
        'Kashi Vishwanath Temple Trust',
        'Flowers, Bilva leaves, Milk, Honey, Fruits, Incense and Sweets',
        'Shiva',
        'January',
        'December',
        'http://www.kvtemple.com',
        20000000,
        'November',
        'June',
        'Hindu',
        'Jyotirlinga',
        'No'
    ),
    (
        2,
        'Kali Pith',
        1800,
        'Kalighat Temple',
        'Kolkata',
        'West Bengal',
        'India',
        'Kalighat Temple Committee',
        'flowers, Red cloth, Sindoor, Coconuts, Sweets, Incense',
        'Kali',
        'January',
        'December',
        'http://www.kalighattemple.com',
        10000000,
        'October',
        'July',
        'Hindu',
        'Shaktipeeth',
        'No'
    ),
    (
        3,
        'Fire Temple of Udwada',
        1740,
        'Fire Temple of Udwada',
        'Udwada',
        'Gujarat',
        'India',
        'Zoroastrian Committee',
        'Fruits, Flowers, Sandalwood',
        'Ahura Mazda',
        'January',
        'December',
        'http://www.udwadafiretemple.com',
        50000,
        'November',
        'March',
        'Zoroastrianism',
        'Zoroastrian Temples',
        'No'
    ),
    (
        4,
        'Zoroastrian Centre of Canada',
        1990,
        'Zoroastrian Centre',
        'Toronto',
        'Ontario',
        'Canada',
        'Zoroastrian Committee',
        'Donations',
        'Ahura Mazda',
        'January',
        'December',
        'http://www.zoroastriancentre.com',
        30000,
        'March',
        'July',
        'Zoroastrianism',
        'Zoroastrian Temples',
        'No'
    ),
    (
        5,
        'Yazd Fire Temple',
        400,
        'Yazd Fire Temple',
        'Yazd',
        'Yazd',
        'Iran',
        'Zoroastrian Committee',
        'Flowers, Fruits and Incense',
        'Ahura Mazda',
        'January',
        'December',
        'http://www.yazdfiretemple.com',
        50000,
        'October',
        'March',
        'Zoroastrianism',
        'Zoroastrian Temples',
        'No'
    ),
    (
        6,
        'The Sanatorium Fire Temple',
        1900,
        'Sanatorium Fire Temple',
        'Johannesburg',
        'Gauteng',
        'South Africa',
        'Zoroastrian Committee',
        'Flowers, Fruits and Incense',
        'Ahura Mazda',
        'January',
        'December',
        'http://www.sanatoriumfiretemple.com',
        5000,
        'March',
        'August',
        'Zoroastrianism',
        'Zoroastrian Temples',
        'No'
    ),
(
    7,
    'Gurdwara Sahib Dasmesh Darbar',
    2000,
    'Gurdwara Sahib Dasmesh Darbar',
    'Toronto',
    'Ontario',
    'Canada',
    'Gurdwara Committee',
    'Karah Prasad, Flowers, Donations',
    'Guru Nanak',
    'January',
    'December',
    'http://www.gurdwarasahib.com',
    300000,
    'September',
    'February',
    'Sikh',
    'Sikh Temples',
    'No'
),
(
    8,
    'Al-Masjid al-Haram',
    630,
    'Al-Masjid al-Haram',
    'Mecca',
    'Makkah',
    'Saudi Arabia',
    'Saudi Government',
    'Prayers, Charity, Gratitude',
    'Allah',
    'January',
    'December',
    'http://www.haramain.gov.sa',
    15000000,
    'Hajj',
    'June',
    'Islam',
    'Mosques',
    'Yes'
),
(
    9,
    'Al-Masjid an-Nabawi',
    622,
    'Al-Masjid an-Nabawi',
    'Medina',
    'Al Madinah',
    'Saudi Arabia',
    'Saudi Government',
    'Prayers, Charity, Gratitude',
    'Allah',
    'January',
    'December',
    'http://www.madinah.gov.sa',
    15000000,
    'Hajj',
    'June',
    'Islam',
    'Mosques',
    'Yes'
),
(
    10,
    'Shah Jahan Mosque',
    1647,
    'Shah Jahan Mosque',
    'Thatta',
    'Sindh',
    'Pakistan',
    'Mosque Committee',
    'Donations',
    'Allah',
    'January',
    'December',
    'http://www.shahjahanmosque.com',
    500000,
    'May',
    'November',
    'Islam',
    'Mosques',
    'No'
),
(
    11,
    'Sultan Ahmed Mosque',
    1616,
    'Sultan Ahmed Mosque',
    'Istanbul',
    'Istanbul',
    'Turkey',
    'Mosque Committee',
    'Donations',
    'Allah',
    'January',
    'December',
    'http://www.blue mosque.com',
    3000000,
    'June',
    'February',
    'Islam',
    'Mosques',
    'No'
),
(
    12,
    'Al-Omari Mosque',
    640,
    'Al-Omari Mosque',
    'Damascus',
    'Damascus',
    'Syria',
    'Mosque Committee',
    'Donations',
    'Allah',
    'January',
    'December',
    'http://www.al-omari.com',
    200000,
    'May',
    'August',
    'Islam',
    'Mosques',
    'No'
),
(
    13,
    'Amarnath',
    3000,
    'Amarnath Cave',
    'Anantnag',
    'Jammu',
    'India',
    'Amarnath Shrine Board',
    'Holy water, Milk, Flowers, Ghee, and Sweets',
    'Shiva',
    'July',
    'August',
    'http://www.amarnathji.com',
    500000,
    'August',
    'January',
    'Hindu',
    'Shiva Temple',
    'Yes'
),
(
    14,
    'Kedarnath',
    800,
    'Kedarnath Temple',
    'Kedarnath',
    'Uttarakhand',
    'India',
    'Kedarnath Temple Committee',
    'Bila leaves, Flowers, Holy water, Sweets and Dry Fruits',
    'Shiva',
    'May',
    'November',
    'http://www.kedarnathtemple.com',
    1000000,
    'June',
    'October',
    'Hindu',
    'Jyotirlinga, Chaar Dham',
    'No'
),
(
    15,
    'Badrinath',
    800,
    'Badrinath Temple',
    'Badrinath',
    'Uttarakhand',
    'India',
    'Badrinath Temple Committee',
    'Tulsi Leaves, Flowers, Holy Water, and Dry Fruits',
    'Vishnu',
    'May',
    'October',
    'http://www.badrinath-temple.com',
    800000,
    'June',
    'January',
    'Hindu',
    'Chaar Dham',
    'No'
),
(
    16,
    'Naina Devi',
    1978,
    'Naina Devi Temple',
    'Nainital',
    'Uttarakhand',
    'India',
    'Naina Devi Temple Trust',
    'Flowers, Fruits, Sweets, and Sindoor',
    'Durga',
    'January',
    'December',
    'http://www.nainadevi.com',
    500000,
    'September',
    'February',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    17,
    'Hinglaj Mata Temple',
    3000,
    'Hinglaj Mata Temple',
    'Hingol',
    'Balochistan',
    'Pakistan',
    'Hinglaj Mata Committee',
    'Flowers, Coconuts, Sweets, and Rice',
    'Mata Hinglaj',
    'January',
    'December',
    'http://www.hinglajtemple.com',
    200000,
    'April',
    'November',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    18,
    'Dakshayani Devi Temple',
    1000,
    'Dakshayani Devi Temple',
    'Kerala',
    'Kerala',
    'India',
    'Dakshayani Devi Trust',
    'Flowers, Coconuts, Sweets, and Rice',
    'Dakshayani',
    'January',
    'December',
    'http://www.dakshayani.com',
    100000,
    'April',
    'August',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    19,
    'Siddhivinayak Temple',
    1801,
    'Siddhivinayak Temple',
    'Mumbai',
    'Maharashtra',
    'India',
    'Siddhivinayak Temple Trust',
    'Flowers, Modak, Coconuts',
    'Ganesh',
    'January',
    'December',
    'http://www.siddhivinayaktemple.in',
    3000000,
    'September',
    'February',
    'Hindu',
    'Hindu Temples',
    'No'
),
(
    20,
    'Shakeshwari Temple',
    1900,
    'Shakeshwari Temple',
    'Kolkata',
    'West Bengal',
    'India',
    'Shakeshwari Temple Committee',
    'Flowers, Sweets, Fruits and Incense',
    'Kali',
    'January',
    'December',
    'http://www.shakeshwari.com',
    100000,
    'October',
    'March',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    21,
    'Kali Ghat',
    1800,
    'Kali Ghat Temple',
    'Kolkata',
    'West Bengal',
    'India',
    'Kali Ghat Temple Committee',
    'Flowers, Sweets, Fish, and Red Cloth',
    'Kali',
    'January',
    'December',
    'http://www.kaligathtemple.com',
    1500000,
    'October',
    'February',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    22,
    'Rangnath Swamy Temple',
    2000,
    'Rangnath Swamy Temple',
    'Tamil Nadu',
    'Tamil Nadu',
    'India',
    'Rangnath Temple Trust',
    'Flowers, Fruits, Sweets, and Rice',
    'Vishnu',
    'January',
    'December',
    'http://www.rangnathtemple.com',
    200000,
    'October',
    'July',
    'Hindu',
    'Hindu Temples',
    'No'
),
(
    23,
    'Ram Mandir',
    2020,
    'Ram Mandir',
    'Ayodhya',
    'Uttar Pradesh',
    'India',
    'Ram Janmabhoomi Trust',
    'Flowers,Fruits, Sweets, Tulsi leaves, and Incense',
    'Ram',
    'January',
    'December',
    'http://www.rammandir.com',
    5000000,
    'November',
    'July',
    'Hindu',
    'Hindu Temples',
    'No'
),
(
    24,
    'Golden Temple',
    1577,
    'Harmandir Sahib',
    'Amritsar',
    'Punjab',
    'India',
    'SGPC',
    'Karah Prasad, Flowers, Donations',
    'Guru Nanak',
    'January',
    'December',
    'http://www.srmt.gov.in',
    20000000,
    'November',
    'May',
    'Sikh',
    'Sikh Temples',
    'No'
),
(
    25,
    'Gurdwara Janam Asthan',
    1600,
    'Gurdwara Janam Asthan',
    'Nankana Sahib',
    'Nankana Sahib',
    'Pakistan',
    'Gurdwara Committee',
    'Karah Prasad, Flowers, Donations',
    'Guru Nanak',
    'January',
    'December',
    'http://www.gurdwarajanam.com',
    1000000,
    'November',
    'February',
    'Sikh',
    'Sikh Temples',
    'No'
),
(
    26,
    'Gurdwara Anandpur Sahib',
    1700,
    'Gurdwara Anandpur Sahib',
    'Anandpur Sahib',
    'Punjab',
    'India',
    'Gurdwara Committee',
    'Karah Prasad, Flowers, Seva',
    'Guru Gobind Singh',
    'January',
    'December',
    'http://www.gurdwaraanandpur.com',
    1500000,
    'September',
    'March',
    'Sikh',
    'Sikh Temples',
    'No'
),
(
    27,
    'Gurdwara Sahib Manikaran',
    1700,
    'Gurdwara Sahib',
    'Manikaran',
    'Himachal Pradesh',
    'India',
    'Gurdwara Committee',
    'Karah Prasad, Flowers, Donations',
    'Guru Nanak',
    'January',
    'December',
    'http://www.gurdwarasahib.com',
    500000,
    'November',
    'August',
    'Sikh',
    'Sikh Temples',
    'No'
),
(
    29,
    'Hassan II Mosque',
    1993,
    'Hassan II Mosque',
    'Casablanca',
    'Casablanca',
    'Morocco',
    'Mosque Committee',
    'Donations',
    'Allah',
    'January',
    'December',
    'http://www.hassanh2mosque.com',
    1000000,
    'Ramadan',
    'July',
    'Islam',
    'Mosques',
    'No'
),
(
    30,
    'Holy Trinity Cathedral',
    1955,
    'Holy Trinity Cathedral',
    'Addis Ababa',
    'Addis Ababa',
    'Ethiopia',
    'Cathedral Committee',
    'Flowers, candles, and Donations',
    'God',
    'January',
    'December',
    'http://www.holytrinitycathedral.com',
    500000,
    'January',
    'September',
    'Christianity',
    'Cathedrals',
    'No'
),
(
    31,
    'St. Basil\'s Cathedral',
    1561,
    'St. Basil\'s Cathedral',
    'Moscow',
    'Moscow',
    'Russia',
    'Cathedral Committee',
    'Flowers, candles, and Donations',
    'God',
    'January',
    'December',
    'http://www.stbasilcathedral.com',
    3000000,
    'June',
    'December',
    'Christianity',
    'Cathedrals',
    'No'
),
(
    32,
    'The Church of the Holy Sepulchre',
    335,
    'The Church of the Holy Sepulchre',
    'Jerusalem',
    'Jerusalem',
    'Israel',
    'Church Committee',
    'Donations',
    'God',
    'January',
    'December',
    'http://www.holysepulchre.com',
    4000000,
    'April',
    'November',
    'Christianity',
    'Churches',
    'No'
),
(
    33,
    'St. Paul\'s Cathedral',
    1708,
    'St. Paul\'s Cathedral',
    'London',
    'England',
    'United Kingdom',
    'Cathedral Committee',
    'Flowers, candles, and Donations',
    'God',
    'January',
    'December',
    'http://www.stpaulscathedral.org.uk',
    2000000,
    'December',
    'August',
    'Christianity',
    'Cathedrals',
    'No'
),
(
    34,
    'St. Mary\'s Cathedral',
    2000,
    'St. Mary\'s Cathedral',
    'Sydney',
    'New South Wales',
    'Australia',
    'Cathedral Committee',
    'Flowers, candles, and Donations',
    'God',
    'January',
    'December',
    'http://www.stmarycathedral.org.au',
    1000000,
    'December',
    'June',
    'Christianity',
    'Cathedrals',
    'No'
),
(
    35,
    'Notre Dame Cathedral',
    1163,
    'Notre Dame Cathedral',
    'Paris',
    'Île-de-France',
    'France',
    'Cathedral Committee',
    'Donations',
    'God',
    'January',
    'December',
    'http://www.notredameparis.com',
    5000000,
    'May',
    'October',
    'Christianity',
    'Cathedrals',
    'No'
),
(
    36,
    'The Temple of Emerald Buddha',
    1782,
    'The Temple of Emerald Buddha',
    'Bangkok',
    'Bangkok',
    'Thailand',
    'Temple Committee',
    'Flowers, Incense, Candles, and Lotus buds',
    'Buddha',
    'January',
    'December',
    'http://www.emeraldbuddha.com',
    1000000,
    'January',
    'October',
    'Buddhism',
    'Buddhist Temples',
    'No'
),
(
    37,
    'Angkor Wat',
    1150,
    'Angkor Wat',
    'Siem Reap',
    'Siem Reap',
    'Cambodia',
    'Temple Committee',
    'Donations',
    'Vishnu',
    'January',
    'December',
    'http://www.angkorwat.com',
    2000000,
    'January',
    'July',
    'Buddhism',
    'Buddhist Temples',
    'No'
),
(
    38,
    'Boudha Nath Stupa',
    600,
    'Boudha Nath Stupa',
    'Kathmandu',
    'Bagmati',
    'Nepal',
    'Stupa Committee',
    'Flowers, Incense, Candles, and Lotus buds',
    'Buddha',
    'January',
    'December',
    'http://www.boudhanathstupa.com',
    1500000,
    'April',
    'August',
    'Buddhism',
    'Buddhist Stupas',
    'No'
),
(
    39,
    'Maha Bodhi Temple',
    250,
    'Maha Bodhi Temple',
    'Bodh Gaya',
    'Bihar',
    'India',
    'Temple Committee',
    'Flowers, Incense, Candles',
    'Buddha',
    'January',
    'December',
    'http://www.mahabodhitemple.com',
    3000000,
    'December',
    'July',
    'Buddhism',
    'Buddhist Temples',
    'No'
),
(
    40,
    'Uluwatu Temple',
    1990,
    'Uluwatu Temple',
    'Bali',
    'Bali',
    'Indonesia',
    'Temple Committee',
    'Flowers, Incense, Candles, and Lotus buds',
    'Buddha',
    'January',
    'December',
    'http://www.uluwatutemple.com',
    1000000,
    'April',
    'October',
    'Hindu',
    'Balinese Hindu Temples',
    'No'
),
(
    41,
    'Jain Temple, Ranakpur',
    1437,
    'Jain Temple, Ranakpur',
    'Rajasthan',
    'Rajasthan',
    'India',
    'Jain Committee',
    'Donations',
    'Mahavira',
    'January',
    'December',
    'http://www.jainranakpur.com',
    300000,
    'October',
    'June',
    'Jainism',
    'Jain Temples',
    'No'
),
(
    42,
    'Jain Temple, Khajuraho',
    1000,
    'Jain Temple, Khajuraho',
    'Madhya Pradesh',
    'Madhya Pradesh',
    'India',
    'Jain Committee',
    'Flowers, Fruits, rice, Sweets, and Incense',
    'Mahavira',
    'January',
    'December',
    'http://www.jainkhajuraho.com',
    200000,
    'August',
    'March',
    'Jainism',
    'Jain Temples',
    'No'
),
(
    43,
    'Jain Temple, Kulpakji',
    500,
    'Jain Temple, Kulpakji',
    'Telangana',
    'Telangana',
    'India',
    'Jain Committee',
    'Flowers, Fruits, rice, Sweets, and Incense',
    'Mahavira',
    'January',
    'December',
    'http://www.jainkulpakji.com',
    100000,
    'November',
    'September',
    'Jainism',
    'Jain Temples',
    'No'
),
(
    44,
    'Kirti Garbha Temple',
    700,
    'Kirti Garbha Temple',
    'China',
    'China',
    'China',
    'Temple Committee',
    'Flowers, Fruits, rice, Sweets, and Incense',
    'Buddha',
    'January',
    'December',
    'http://www.kirti.com',
    200000,
    'March',
    'October',
    'Buddhism',
    'Buddhist Temples',
    'No'
),
(
    45,
    'Jain Temple, Melbourne',
    1990,
    'Jain Temple, Melbourne',
    'Melbourne',
    'Victoria',
    'Australia',
    'Jain Committee',
    'Donations',
    'Mahavira',
    'January',
    'December',
    'http://www.jainmelbourne.com',
    500000,
    'November',
    'August',
    'Jainism',
    'Jain Temples',
    'No'
),
(
    46,
    'Dilwara Temple',
    1031,
    'Dilwara Temple',
    'Rajasthan',
    'Rajasthan',
    'India',
    'Jain Committee',
    'Flowers, Fruits, and Incense',
    'Mahavira',
    'January',
    'December',
    'http://www.dilwara.com',
    300000,
    'October',
    'February',
    'Jainism',
    'Jain Temples',
    'No'
),
(
    47,
    'Agiary Mumbai',
    1700,
    'Agiary',
    'Mumbai',
    'Maharashtra',
    'India',
    'Parsi Committee',
    'Fruits, Flowers, Sandalwood',
    'Ahura Mazda',
    'January',
    'December',
    'http://www.agiary.com',
    500000,
    'September',
    'July',
    'Zoroastrianism',
    'Zoroastrian Temples',
    'No'
),
(
    48,
    'Kamakya',
    1000,
    'Kamakya Temple',
    'Guwahati',
    'Assam',
    'India',
    'Kamakya Temple Trust',
    'Flowers, Red cloth, Coconuts, Sweets',
    'Kamakya',
    'April',
    'June',
    'http://www.kamakhi.gov.in',
    5000000,
    'April',
    'August',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    49,
    'Vaishno Devi',
    1986,
    'Vaishno Devi Temple',
    'Katra',
    'Jammu',
    'India',
    'Vaishno Devi Shrine Board',
    'Flowers, Coconut, Red Chunari, Sweets, Incense and Dry Fruits',
    'Durga',
    'January',
    'December',
    'http://www.maavaishnodevi.org',
    8000000,
    'March',
    'August',
    'Hindu',
    'Shaktipeeth',
    'No'
),
(
    50,
    'Banke Bihari',
    1864,
    'Banke Bihari Temple',
    'Vrindavan',
    'Uttar Pradesh',
    'India',
    'Banke Bihari Mandir Trust',
    'Sweets, Fruits, Flowers, Clothes and sometimes Toys',
    'Krishna',
    'January',
    'December',
    'http://www.banke-bihari-temple.com',
    3000000,
    'September',
    'April',
    'Hindu',
    'Hindu Temples',
    'No'
);